export const AWARDS = [
  {
    id: "ma-astrology",
    year: "2016",
    place: "Erode",
    titleTa: "ஜோதிஷ வாசஸ்பதி · M.A. (Astrology)",
    titleEn: "Jyotish Vachaspati · M.A. (Astrology)",
    orgTa: "சப்தரிஷி ஜோதிட அறிவியல் பயிற்சி & ஆராய்ச்சி மையம் · அண்ணாமலைப் பல்கலைக்கழகம்",
    orgEn: "Saptharishi Astrological Sciences Training & Research Centre, in collaboration with Annamalai University",
    noteTa: "M.A. Astrology பயிற்சி மற்றும் ஜோதிஷ வாசஸ்பதி சிறப்புப் பட்டம் தொடர்பான சான்று. பதிவு எண்: 82114DR092.",
    noteEn: "Record of M.A. Astrology studies and the Jyotish Vachaspati honour. Enrolment no. 82114DR092.",
    image: "/images/awards/jyotish-vachaspati-2016.jpeg",
    category: "degrees",
  },
  {
    id: "ma-plaque",
    year: "2016",
    place: "Annamalai Nagar",
    titleTa: "M.A., (Astrology) — அண்ணாமலைப் பல்கலைக்கழகப் பலகை",
    titleEn: "M.A. (Astrology) — Annamalai University plaque",
    orgTa: "Annamalai University · Saptharishi Academy, Madurai",
    orgEn: "Annamalai University in collaboration with Saptharishi Academy, Madurai",
    noteTa: "12 ராசி சின்னங்களுடன் கூடிய வட்டப் பலகை. பெயர்: T. ELANGHO.",
    noteEn: "Circular zodiac plaque awarded to T. Elangho.",
    image: "/images/awards/annamalai-ma-astrology-plaque.jpeg",
    category: "degrees",
  },
  {
    id: "phd-colombo",
    year: "2018",
    place: "Colombo",
    titleTa: "Doctor of Philosophy (Astrology)",
    titleEn: "Doctor of Philosophy (Astrology)",
    orgTa: "Medicina Alternativa · Open International University for Complementary Medicines",
    orgEn: "Medicina Alternativa, affiliated with the Open International University for Complementary Medicines",
    noteTa: "ஜனவரி 2018, கொழும்பு. பதிவு எண் 16506. ஜோதிடப் பிரிவில் Ph.D. (Astrology) பின்னொட்டு அனுமதிக்கப்பட்ட சான்றிதழ். இது மருத்துவப் பயிற்சி உரிமை அல்ல.",
    noteEn: "January 2018, Colombo. Registration no. 16506. Certificate authorising the suffix Ph.D. (Astrology). This is presented as an astrology credential, not as a licence to practise medicine.",
    image: "/images/awards/phd-medicina-alternativa-2018.jpeg",
    category: "degrees",
  },
  {
    id: "phd-calcutta",
    year: "2018",
    place: "Kolkata",
    titleTa: "Ph.D. in Astrology",
    titleEn: "Ph.D. in Astrology",
    orgTa: "Alternative Medical Council Calcutta",
    orgEn: "Alternative Medical Council Calcutta",
    noteTa: "29.01.2018 தேதியிட்ட ஜோதிடத்தில் Doctor of Philosophy சான்றிதழ். மருத்துவப் பயிற்சியாளர் என்ற அறிவிப்பாக இதைக் காட்டவில்லை.",
    noteEn: "Certificate dated 29 January 2018 conferring a Doctor of Philosophy in Astrology. Shown as historical/biographical material, not as a claim of medical practice.",
    image: "/images/awards/phd-amcc-calcutta-2018.jpeg",
    category: "degrees",
  },
  {
    id: "jothida-samrat-cert",
    year: "2018",
    place: "Erode",
    titleTa: "ஜோதிட சாம்ராட் — சிறப்பு விருது",
    titleEn: "Jothida Samrat — Special Astrology Award",
    orgTa: "அகில இந்திய ஜோதிடர் மாநாடு",
    orgEn: "All India Astrologer Conference",
    noteTa: "11–12 ஆகஸ்ட் 2018, சக்தி மஹால், பெருந்துறை ரோடு, ஈரோடு. மிதுனரிஷி முனைவர் T. இளங்கோ அவர்களுக்கு வழங்கப்பட்ட சான்றிதழ்.",
    noteEn: "11–12 August 2018, Sakthi Mahal, Perundurai Road, Erode. Certificate honouring Mithuna Rishi Dr. T. Elangho.",
    image: "/images/awards/jothida-samrat-certificate-2018.jpeg",
    category: "awards",
  },
  {
    id: "jothida-samrat-plaque",
    year: "2018",
    place: "Erode",
    titleTa: "ஜோதிட சாம்ராட் பலகை",
    titleEn: "Jothida Samrat plaque",
    orgTa: "All India Astrologer Conference",
    orgEn: "All India Astrologer Conference",
    noteTa: "ஈரோட்டில் நடைபெற்ற அகில இந்திய ஜோதிடர் மாநாட்டில் சேலம் முனைவர் T. இளங்கோ திருநாவுக்கரசு அவர்களுக்கு வழங்கப்பட்ட பலகை.",
    noteEn: "Plaque presented at the All India Astrologer Conference in Erode to Dr. T. Elangho Thirunavukkarasu of Salem.",
    image: "/images/awards/jothida-samrat-plaque-2018.jpeg",
    category: "awards",
  },
  {
    id: "vitthakar",
    year: "2023",
    place: "Erode",
    titleTa: "ஜோதிஷ வித்தகர்",
    titleEn: "Jyotisha Vitthakar",
    orgTa: "உலகத் தமிழ் ஜோதிடர்கள் மஹா ஜன சபை",
    orgEn: "World Tamil Astrologers Maha Jana Sabha",
    noteTa: "16–17 டிசம்பர் 2023, 12-வது ஜோதிட மாநாடு, மல்லிகை அரங்கம், ஈரோடு.",
    noteEn: "16–17 December 2023, 12th Astrology Conference, Malligai Arangam, Erode.",
    image: "/images/awards/jyotisha-vitthakar-2023.jpeg",
    category: "conferences",
  },
  {
    id: "traditional-expert",
    year: "2025",
    place: "Erode",
    titleTa: "பாரம்பரிய ஜோதிட வித்தகர்",
    titleEn: "Traditional Astrology Expert",
    orgTa: "அகில உலக உண்மை ஜோதிடர்கள் சங்கம் · மகாஜெயம் அஸ்ட்ரோ ஆராய்ச்சி பயிற்சி மையம்",
    orgEn: "Universal True Astrologers Association · Mahajeyam Astro Research and Training Centre",
    noteTa: "ஜோதிட சிறப்பு மாநாடு / பட்டிமன்றம், ஈரோடு. சிறப்பு உரைக்காக வழங்கப்பட்ட பலகை.",
    noteEn: "Special astrology conference and debate, Erode. Plaque for a distinguished address.",
    image: "/images/awards/traditional-expert-plaque-2025.jpeg",
    category: "awards",
  },
] as const;

export const TIMELINE = [
  { year: "2016", ta: "அண்ணாமலைப் பல்கலைக்கழகத்துடன் இணைந்த சப்தரிஷி மையத்தில் M.A. Astrology பயிற்சி மற்றும் ஜோதிஷ வாசஸ்பதி சிறப்புப் பட்டம்.", en: "M.A. Astrology studies with Saptharishi Centre in collaboration with Annamalai University, and the Jyotish Vachaspati honour." },
  { year: "2018", ta: "ஈரோட்டில் அகில இந்திய ஜோதிடர் மாநாட்டில் ஜோதிட சாம்ராட் விருது. அதே ஆண்டு ஜோதிடத்தில் Ph.D. தொடர்பான சான்றிதழ்கள்.", en: "Jothida Samrat honour at the All India Astrologer Conference in Erode, and astrology Ph.D. certificates in the same year." },
  { year: "2023", ta: "உலகத் தமிழ் ஜோதிடர்கள் மஹா ஜன சபையின் 12-வது மாநாட்டில் ஜோதிஷ வித்தகர் அங்கீகாரம்.", en: "Jyotisha Vitthakar recognition at the 12th conference of the World Tamil Astrologers Maha Jana Sabha." },
  { year: "2025", ta: "ஈரோட்டில் பாரம்பரிய ஜோதிட வித்தகர் பலகை — மாநாடு மற்றும் பட்டிமன்றப் பங்கேற்பு.", en: "Traditional Astrology Expert plaque in Erode for conference and debate participation." },
] as const;
