export const RASIS = [
  {
    id: "mesham",
    ta: "மேஷம்",
    en: "Mesham",
    latin: "Aries",
    symbol: "♈",
    elementTa: "தீ",
    elementEn: "Fire",
    planetTa: "செவ்வாய்",
    planetEn: "Mars",
    traitsTa: "தைரியம், முன்முனைப்பு, தலைமைப் பண்பு. புதிய தொடக்கங்களில் ஆர்வம்.",
    traitsEn: "Courage, initiative and leadership. Drawn to new beginnings.",
  },
  {
    id: "rishabam",
    ta: "ரிஷபம்",
    en: "Rishabam",
    latin: "Taurus",
    symbol: "♉",
    elementTa: "நிலம்",
    elementEn: "Earth",
    planetTa: "சுக்கிரன்",
    planetEn: "Venus",
    traitsTa: "நிலைத்தன்மை, அழகு விருப்பம், பொறுமை மற்றும் நடைமுறை அணுகுமுறை.",
    traitsEn: "Stability, love of beauty, patience and a practical outlook.",
  },
  {
    id: "mithunam",
    ta: "மிதுனம்",
    en: "Mithunam",
    latin: "Gemini",
    symbol: "♊",
    elementTa: "காற்று",
    elementEn: "Air",
    planetTa: "புதன்",
    planetEn: "Mercury",
    traitsTa: "தொடர்புத் திறன், கற்றல் ஆர்வம், பல்துறை சிந்தனை.",
    traitsEn: "Communication, curiosity and versatile thinking.",
  },
  {
    id: "kadagam",
    ta: "கடகம்",
    en: "Kadagam",
    latin: "Cancer",
    symbol: "♋",
    elementTa: "நீர்",
    elementEn: "Water",
    planetTa: "சந்திரன்",
    planetEn: "Moon",
    traitsTa: "குடும்ப பற்று, உணர்ச்சி ஆழம், பாதுகாப்பு உணர்வு.",
    traitsEn: "Family bonding, emotional depth and a protective nature.",
  },
  {
    id: "simmam",
    ta: "சிம்மம்",
    en: "Simmam",
    latin: "Leo",
    symbol: "♌",
    elementTa: "தீ",
    elementEn: "Fire",
    planetTa: "சூரியன்",
    planetEn: "Sun",
    traitsTa: "கௌரவம், தன்னம்பிக்கை, படைப்பாற்றல் மற்றும் தலைமை.",
    traitsEn: "Dignity, confidence, creativity and leadership.",
  },
  {
    id: "kanni",
    ta: "கன்னி",
    en: "Kanni",
    latin: "Virgo",
    symbol: "♍",
    elementTa: "நிலம்",
    elementEn: "Earth",
    planetTa: "புதன்",
    planetEn: "Mercury",
    traitsTa: "நுணுக்கம், ஒழுங்கு, பகுப்பாய்வு மற்றும் சேவை மனப்பான்மை.",
    traitsEn: "Precision, order, analysis and a service-minded nature.",
  },
  {
    id: "thulam",
    ta: "துலாம்",
    en: "Thulam",
    latin: "Libra",
    symbol: "♎",
    elementTa: "காற்று",
    elementEn: "Air",
    planetTa: "சுக்கிரன்",
    planetEn: "Venus",
    traitsTa: "சமநிலை, நீதி உணர்வு, கலை ரசனை மற்றும் இணக்கம்.",
    traitsEn: "Balance, fairness, aesthetic sense and harmony.",
  },
  {
    id: "viruchigam",
    ta: "விருச்சிகம்",
    en: "Viruchigam",
    latin: "Scorpio",
    symbol: "♏",
    elementTa: "நீர்",
    elementEn: "Water",
    planetTa: "செவ்வாய்",
    planetEn: "Mars",
    traitsTa: "ஆழம், உறுதி, ஆராய்ச்சித் திறன் மற்றும் உள்வலிமை.",
    traitsEn: "Depth, determination, research ability and inner strength.",
  },
  {
    id: "dhanusu",
    ta: "தனுசு",
    en: "Dhanusu",
    latin: "Sagittarius",
    symbol: "♐",
    elementTa: "தீ",
    elementEn: "Fire",
    planetTa: "குரு",
    planetEn: "Jupiter",
    traitsTa: "ஞானத் தேடல், பயண ஆர்வம், நேர்மை மற்றும் விரிவான பார்வை.",
    traitsEn: "Wisdom-seeking, travel, honesty and a broad outlook.",
  },
  {
    id: "magaram",
    ta: "மகரம்",
    en: "Magaram",
    latin: "Capricorn",
    symbol: "♑",
    elementTa: "நிலம்",
    elementEn: "Earth",
    planetTa: "சனி",
    planetEn: "Saturn",
    traitsTa: "பொறுப்பு, கடின உழைப்பு, ஒழுக்கம் மற்றும் நீண்டகால இலக்கு.",
    traitsEn: "Responsibility, hard work, discipline and long-term aims.",
  },
  {
    id: "kumbam",
    ta: "கும்பம்",
    en: "Kumbam",
    latin: "Aquarius",
    symbol: "♒",
    elementTa: "காற்று",
    elementEn: "Air",
    planetTa: "சனி",
    planetEn: "Saturn",
    traitsTa: "சுதந்திரம், சமூக சிந்தனை, புத்தாக்கம் மற்றும் மனிதநேயம்.",
    traitsEn: "Independence, social thought, innovation and humanitarian ideals.",
  },
  {
    id: "meenam",
    ta: "மீனம்",
    en: "Meenam",
    latin: "Pisces",
    symbol: "♓",
    elementTa: "நீர்",
    elementEn: "Water",
    planetTa: "குரு",
    planetEn: "Jupiter",
    traitsTa: "கருணை, கற்பனை, ஆன்மீக உணர்வு மற்றும் இரக்கம்.",
    traitsEn: "Compassion, imagination, spiritual sensitivity and kindness.",
  },
] as const;

export type Rasi = (typeof RASIS)[number];
