export const VIDEOS = [
  {
    id: "astrology",
    file: "/videos/what-is-astrology.mp4",
    featured: true,
    category: "explanations",
    ta: "ஜோதிடம் என்றால் என்ன",
    en: "What is Astrology",
    noteTa: "ஜோதிட அடிப்படைகள் குறித்த விளக்கக் காணொளி.",
    noteEn: "An introductory explanation of astrology.",
  },
  {
    id: "directions",
    file: "/videos/directions.mp4",
    featured: false,
    category: "explanations",
    ta: "திசைகள் — ஜோதிட விளக்கம்",
    en: "Directions in Astrology",
    noteTa: "திசைகள் குறித்த ஜோதிடப் பார்வை.",
    noteEn: "Astrological notes on directions.",
  },
  {
    id: "love-marriage",
    file: "/videos/love-marriage.mp4",
    featured: false,
    category: "consultations",
    ta: "காதல் திருமணம் — ஜோதிடக் குறிப்பு",
    en: "Love Marriage — Astrological Note",
    noteTa: "திருமணம் குறித்த ஜோதிட விளக்கம். முடிவுகள் உத்தரவாதம் அல்ல.",
    noteEn: "An astrological discussion of marriage. Outcomes are not guaranteed.",
  },
  {
    id: "child-chart",
    file: "/videos/child-birthchart.mp4",
    featured: false,
    category: "explanations",
    ta: "குழந்தை ஜாதகம் மற்றும் பெற்றோர்",
    en: "A Child’s Birth Chart and Parents",
    noteTa: "குழந்தை ஜாதகம் குடும்பச் சூழலுடன் எப்படிப் பார்க்கப்படுகிறது என்பதற்கான விளக்கம்.",
    noteEn: "How a child’s birth chart is traditionally read in relation to the family.",
  },
] as const;

export const VIDEO_FILTERS = [
  { id: "all", ta: "அனைத்தும்", en: "All" },
  { id: "rasipalan", ta: "ராசிபலன்", en: "Rasipalan" },
  { id: "explanations", ta: "ஜோதிட விளக்கங்கள்", en: "Explanations" },
  { id: "nakshatras", ta: "நட்சத்திர விளக்கங்கள்", en: "Nakshatras" },
  { id: "events", ta: "நிகழ்ச்சிகள்", en: "Events" },
  { id: "talks", ta: "உரைகள்", en: "Talks" },
  { id: "consultations", ta: "ஆலோசனைகள்", en: "Consultations" },
] as const;
